### PR TITLE
Update to Tailscale 1.0.5

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by nirev** [comment]
Hey, @sbrunner!
thank you for this. Did you actually try generating the package and installing it?

I've been postponing this for a while, but there's and issue that I need to solve:

context:
- up until v0.98 tailscale didn't check if iptables rules were applied or not, and proceeded anyway
- now, since version v.099, it checks if iptables rules were applied, and bails off if they fail
- Synology DSM 6.2 doesn't include all of the netfilter modules that tailscale needs, so iptables set up fails

With that, we could do the following:
1. add a disclaimer that iptables is broken, and modify `synology-tailscale` to disable netfilter rules when starting `tailscale` (easier)
2. compile netfilter modules for DSM and ship it

so if perhaps you could look into this, I'd appreciate

**Comment by vladimir-ch** [comment]
I can confirm that it doesn't work. I've been trying to do this locally for some time now but always without success. I can authenticate, `tailscale status` gives expected output but the `tailscale0` interface is not up.

**Comment by sbrunner** [comment]
I built it and test it basically, I will do some deeper test but you will probably right...

Thanks :-)

**Comment by fqx** [comment]
run tailscale with --netfilter-mode=off can bypass this error.
However, I don't know what is the consequence if ignore iptables.

**Comment by jucor** [comment]
@bradfitz What are the consequences if we ignore tailscale 0.99 `iptables`'s check? Is is a big problem?

**Comment by nirev** [comment]
The consequence is that any inbound/outbound traffic on the tailscale interface will be accepted. 

This is likely what is *already* happening with the Synology package. The thing is just that before v99 tailscale would just ignore if iptables setup failed.

I'll try to update the package this weekend.

**Comment by nirev** [comment]
I was testing this today. 
If you already have a `.state` file with for previous version, you can migrate it to disable netfilter by doing:

```
cd /var/packages/tailscale/target/var
mv tailscale.state tailscale.state.old
sudo jq --arg updated "$(
    jq -r '._daemon' tailscaled.state.old | \
    base64 -d | \
    jq -r 'del(.UsePacketFilter) | .ShieldsUp = false | .oSNAT = false | .NetfilterMode = 0 | @base64'\
  )" \
  '._daemon = $updated' \
  tailscaled.state.old > tailscaled.state
```

So in theory the state file can be automatically migrated, but I'm trying to understand what would be the best option here.
I don't want to break any working set up.

**Comment by jucor** [comment]
And for fresh installs, who are installing Tailscale for the first time, do
we need to do anything?

**Comment by bradfitz** [comment]
Skip 1.0.x and jump to Tailscale build 1.1.335: https://pkgs.tailscale.com/unstable/

That will force netfilter=off mode on Synology for now while we work on making subnet routing also work.

**Pull request closed without merging**
